# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/proj/base-rt.cache/wt [current_project]
set_property parent.project_path /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/proj/base-rt.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.0 [current_project]
set_property ip_repo_paths /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/repo [current_project]
set_property ip_output_repo /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/repo/cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/hdl/system_wrapper.vhd
add_files /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_gpio_input_0/system_axi_gpio_input_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_gpio_input_0/system_axi_gpio_input_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_gpio_input_0/system_axi_gpio_input_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_gpio_led_0/system_axi_gpio_led_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_gpio_led_0/system_axi_gpio_led_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_gpio_led_0/system_axi_gpio_led_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_29/bd_44e3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/bd_44e3_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/bd_44e3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/bd_44e3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_15/bd_44e3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/bd_44e3_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/bd_44e3_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_mdm_1_0/system_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0/user_design/constraints/system_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0/user_design/constraints/system_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_rst_clk_wiz_0_100M_0/system_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_rst_clk_wiz_0_100M_0/system_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_rst_clk_wiz_0_100M_0/system_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_rst_mig_7series_0_81M_0/system_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_rst_mig_7series_0_81M_0/system_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_rst_mig_7series_0_81M_0/system_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_axi_uartlite_1_0/system_axi_uartlite_1_0.xdc]
set_property used_in_synthesis false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/constraints/Arty-S7-50-Master.xdc
set_property used_in_implementation false [get_files /home/mitchellorsucci/DigilentRepos/Arty-S7-50-base-rt/src/constraints/Arty-S7-50-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7s50csga324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
